initial 4.02 import

diff --git a/godi/godi-zarith/patches/patch-aa b/godi/godi-zarith/patches/patch-aa
--- a/godi/godi-zarith/patches/patch-aa
+++ b/godi/godi-zarith/patches/patch-aa
@@ -1,5 +1,68 @@
---- ../../work-ref/zarith-1.2/configure	2013-04-24 13:54:49.000000000 +0200
-+++ ./configure	2013-05-22 10:14:25.956400000 +0200
+--- ../../work-ref/zarith-1.2/configure	2014-05-28 18:25:37.197200000 +0200
++++ ./configure	2014-05-28 18:24:19.462400000 +0200
+@@ -30,7 +30,11 @@
+   cc='gcc'
+   ccopt="-O3 -Wall -Wextra $CFLAGS"
+ fi
+-ar='ar'
++if test -n "$AR"; then
++    ar="$AR"
++else
++    ar='ar'
++fi
+ ocaml='ocaml'
+ ocamlc='ocamlc'
+ ocamlopt='ocamlopt'
+@@ -231,7 +235,7 @@
+ 
+ # directories
+ 
+-if test "$ocamllibdir" = "auto"; then ocamllibdir=`ocamlc -where`; fi
++if test "$ocamllibdir" = "auto"; then ocamllibdir=`ocamlc -where | tr -d '\r'`; fi
+ 
+ # fails on Cygwin:
+ # if test ! -f "$ocamllibdir/caml/mlvalues.h"
+@@ -258,7 +262,7 @@
+ if test $? -eq 1 -a $ocamlfind != "no"; then 
+     instmeth='findlib'
+     if test "$installdir" = "auto"
+-    then installdir=`ocamlfind printconf destdir`; fi
++    then installdir=`ocamlfind printconf destdir | tr -d '\r'`; fi
+ else
+     searchbin install
+     if test $? -eq 1; then instmeth='install'
+@@ -383,6 +387,20 @@
+         ;;
+ esac
+ 
++exec_suffix=''
++so_suffix='.so'
++systype=`uname -s`
++case "$systype" in
++    CYGWIN*)
++	exec_suffix='.exe' 
++	so_suffix='.dll'
++	;;
++    MINGW*)
++	exec_suffix='.exe'
++	so_suffix='.dll'
++	;;
++esac
++
+ # dump Makefile
+ 
+ cat > Makefile <<EOF
+@@ -395,6 +413,8 @@
+ OCAMLMKLIB=$ocamlmklib
+ OCAMLDOC=$ocamldoc
+ OCAMLFLAGS=$mlflags
++EXEC_SUFFIX=$exec_suffix
++DLL_SUFFIX=$so_suffix
+ OCAMLOPTFLAGS=$mloptflags
+ OCAMLINC=$mlinc
+ CFLAGS=$ccinc $ccdef $ccopt
+--- ../../work-ref/zarith-1.2/configure.orig	2013-04-24 13:54:49.000000000 +0200
++++ ./configure.orig	2014-05-28 18:07:44.525600000 +0200
 @@ -231,7 +231,7 @@
  
  # directories
@@ -49,16 +112,16 @@
  OCAMLINC=$mlinc
  CFLAGS=$ccinc $ccdef $ccopt
 --- ../../work-ref/zarith-1.2/META	2012-04-30 21:28:21.000000000 +0200
-+++ ./META	2013-05-22 10:14:25.956400000 +0200
++++ ./META	2014-05-28 18:24:59.008400000 +0200
 @@ -1,5 +1,5 @@
  description = "Arbitrary precision integers"
  requires = ""
 -version = "1.1"
-+version = "1.2"
++version = "1.2.1"
  archive(byte) = "zarith.cma"
  archive(native) = "zarith.cmxa"
 --- ../../work-ref/zarith-1.2/project.mak	2012-12-10 10:47:31.000000000 +0100
-+++ ./project.mak	2013-05-22 10:30:25.699600000 +0200
++++ ./project.mak	2014-05-28 18:07:44.525600000 +0200
 @@ -18,7 +18,9 @@
  else
  OBJSUFFIX    := o
